using CapriKit.Concurrency.Async;
using CapriKit.IO;

namespace CapriKit.AssetPipeline.HotReloading;

internal sealed class HotSwapManager : IDisposable
{
    private readonly TimeSpan MinWaitTime = TimeSpan.FromSeconds(0.5);

    private readonly AssetManager AssetManager;
    private readonly ReadOnlyScopedFileSystem FileSystem;
    private readonly Dictionary<FilePath, List<Reloadable>> Dependents;
    private readonly Dictionary<AssetId, Reloadable> Affected;

    private readonly FileSystemEventQueue PendingFileChanges;
    private readonly HotSwapQueue PendingHotSwaps;

    private DateTime lastFileChange;
    private int detectedFileChanges;

    public HotSwapManager(AssetManager assetManager, ReadOnlyScopedFileSystem fileSystem)
    {
        AssetManager = assetManager;
        FileSystem = fileSystem;
        PendingFileChanges = new FileSystemEventQueue(fileSystem.BasePath);
        lastFileChange = DateTime.MinValue;

        Dependents = [];
        Affected = [];
        PendingHotSwaps = new HotSwapQueue();
    }

    public void Track<TAsset>(AssetId id, Asset<TAsset> asset, IAssetSettings<TAsset> settings)
        where TAsset : class
    {
        var reloadable = new Reloadable<TAsset>(id, asset.Value, settings);
        foreach (var dependency in asset.Dependencies)
        {
            // Match the absolute paths generated by file system events
            var file = FileSystem.GetAbsolutePath(dependency.File);
            if (Dependents.TryGetValue(file, out var list))
            {
                list.Add(reloadable);
            }
            else
            {
                Dependents[file] = [reloadable];
            }
        }
    }

    public void ProcessUpdates()
    {
        var now = DateTime.Now;
        if (PendingFileChanges.Count > detectedFileChanges)
        {
            detectedFileChanges = PendingFileChanges.Count;
            lastFileChange = now;
        }

        if (lastFileChange < (now - MinWaitTime))
        {
            ProcessAffected();
        }

        PendingHotSwaps.HotSwapPending(AssetManager);
    }

    private void ProcessAffected()
    {
        while (PendingFileChanges.TryDequeue(out var @event) && detectedFileChanges > 0)
        {
            if (Dependents.TryGetValue(@event.File, out var list))
            {
                foreach (var asset in list)
                {
                    Affected.Add(asset.Id, asset);
                }
            }
            --detectedFileChanges;
        }

        foreach (var (id, reloadable) in Affected)
        {
            // TODO: It is also possible that re-encoding is still in progress while we get another
            // file change so we should not start more work before FireAndForget marks its task as completed
            // (see overload).

            // TODO: after updating we need to 'retrack' as the dependencies can have changed
            reloadable.Reload(AssetManager, PendingHotSwaps).FireAndForget(ex => { });
        }

        Affected.Clear();
    }

    public void Dispose()
    {
        PendingFileChanges.Dispose();
    }
}
