# Builds caprikit_basisu.dll from the basis_universal submodule.
# Requires CMake and the Visual Studio C++ toolchain.
# Output: <repo>\.build\bin\caprikit_basisu\caprikit_basisu.dll
#
# Rerun this script after updating the basis_universal submodule; it also
# regenerates exports.def so new bu_*/bt_* functions are exported automatically.
param(
    [ValidateSet('Release', 'Debug')]
    [string] $Configuration = 'Release'
)

$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path "$PSScriptRoot\..\..\..").Path
$buildDir = Join-Path $repoRoot '.build\native\caprikit_basisu'
$outDir = Join-Path $repoRoot '.build\bin\caprikit_basisu'

# Find CMake: PATH first, then the default install location.
$cmake = (Get-Command cmake -ErrorAction SilentlyContinue)?.Source ?? 'C:\Program Files\CMake\bin\cmake.exe'
if (-not (Test-Path $cmake)) {
    throw "CMake not found on PATH or at '$cmake'. Install CMake first."
}

# Regenerate exports.def from the C API headers so it never goes stale.
$headers = "$repoRoot\external\basis_universal\encoder\basisu_wasm_api.h",
           "$repoRoot\external\basis_universal\encoder\basisu_wasm_transcoder_api.h"
$names = Select-String -Path $headers -Pattern 'BU_WASM_EXPORT\("([^"]+)"\)' |
    ForEach-Object { $_.Matches[0].Groups[1].Value }
if ($names.Count -eq 0) {
    throw 'No BU_WASM_EXPORT declarations found; did the basis_universal C API move?'
}

$defLines = @(
    '; Generated by build.ps1 from the BU_WASM_EXPORT declarations in'
    '; external/basis_universal/encoder/basisu_wasm_api.h and basisu_wasm_transcoder_api.h.'
    '; Do not edit by hand; rerun build.ps1 to regenerate.'
    'LIBRARY caprikit_basisu'
    'EXPORTS'
) + ($names | ForEach-Object { "    $_" })
$defContent = ($defLines -join "`r`n") + "`r`n"

$defPath = Join-Path $PSScriptRoot 'exports.def'
if ((Test-Path $defPath) -and (Get-Content $defPath -Raw) -eq $defContent) {
    Write-Host "exports.def is up to date ($($names.Count) exports)."
} else {
    Set-Content -Path $defPath -Value $defContent -NoNewline
    Write-Host "exports.def (re)generated ($($names.Count) exports)."
}

& $cmake -S $PSScriptRoot -B $buildDir -A x64
if ($LASTEXITCODE -ne 0) { throw 'CMake configure failed.' }

& $cmake --build $buildDir --config $Configuration
if ($LASTEXITCODE -ne 0) { throw 'CMake build failed.' }

New-Item -ItemType Directory -Force $outDir | Out-Null
Copy-Item (Join-Path $buildDir "$Configuration\caprikit_basisu.dll") $outDir -Force
Write-Host "caprikit_basisu.dll -> $outDir"
